version: '3.0'

services:
  grafana:
    container_name: 'marcusolsson-csv-datasource'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    environment:
      - GF_PLUGIN_ALLOW_LOCAL_MODE=true
      #- GF_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=tma-csv-datasource
      #- GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/tma-csv-datasource
      - ./provisioning:/etc/grafana/provisioning
      - grafana-storage-dev:/var/lib/grafana

volumes:
  grafana-storage-dev:
